# myhorizontalpodautoscaler-crd.yaml

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myhorizontalpodautoscalers.autoscaling.example.com
spec:
  group: autoscaling.example.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    kind: MyHorizontalPodAutoscaler
    plural: myhorizontalpodautoscalers
    singular: myhorizontalpodautoscaler
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            scaleTargetRef:
              type: object
              properties:
                apiVersion:
                  type: string
                kind:
                  type: string
                name:
                  type: string
              required:
                - apiVersion
                - kind
                - name
            minReplicas:
              type: integer
            maxReplicas:
              type: integer
            metrics:
              type: array
              items:
                type: object
                properties:
                  metricType:
                    type: string
                  target:
                    type: object
                    properties:
                      type:
                        type: string
                      value:
                        type: integer
                    required:
                      - type
                      - value
                required:
                  - metricType
                  - target
          required:
            - scaleTargetRef
            - minReplicas
            - maxReplicas
            - metrics
